### ISSUE TITLE
ktools.mint is not a function

### ISSUE THREAD

**Issue by inovatedTeam** [open-koi/koi_tools#9]
I try to submit to set some KOI using arweave address.
but I am getting this error.

![image](https://user-images.githubusercontent.com/14047891/109707611-38c50180-7b4f-11eb-8108-9b9b9ca43680.png)

**Comment by inovatedTeam** [comment]
OK. I solved the issue.
The problem is version.
It is working well on v1.5.0
